// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NationalParksAPI.Models;

namespace NationalParksAPI.Migrations
{
    [DbContext(typeof(NationalParksAPIContext))]
    [Migration("20210402175938_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("NationalParksAPI.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<string>("Established")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ImageURL")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("ParkId");

                    b.HasIndex("StateId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Distance = 236381,
                            Established = "1899-03-02",
                            ImageURL = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Mount_Rainier_from_above_Myrtle_Falls_in_August.JPG/1280px-Mount_Rainier_from_above_Myrtle_Falls_in_August.JPG",
                            Name = "Mount Rainier National Park",
                            StateId = 1
                        },
                        new
                        {
                            ParkId = 2,
                            Distance = 183224,
                            Established = "1902-05-22",
                            ImageURL = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Above_Crater_Lake_%28cropped%29.jpg/1920px-Above_Crater_Lake_%28cropped%29.jpg",
                            Name = "Crater Lake National Park",
                            StateId = 2
                        },
                        new
                        {
                            ParkId = 3,
                            Distance = 265461,
                            Established = "1915-01-26",
                            ImageURL = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/ViewFromSummitofHallett.jpg/1920px-ViewFromSummitofHallett.jpg",
                            Name = "Rocky Mountain State Park",
                            StateId = 3
                        });
                });

            modelBuilder.Entity("NationalParksAPI.Models.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("StateId");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            StateId = 1,
                            Name = "Washington",
                            Region = "Pacific-NorthWest"
                        },
                        new
                        {
                            StateId = 2,
                            Name = "Oregon",
                            Region = "Pacific-NorthWest"
                        },
                        new
                        {
                            StateId = 3,
                            Name = "Colorado",
                            Region = "Mountain-West"
                        });
                });

            modelBuilder.Entity("NationalParksAPI.Models.Park", b =>
                {
                    b.HasOne("NationalParksAPI.Models.State", null)
                        .WithMany("Parks")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NationalParksAPI.Models.State", b =>
                {
                    b.Navigation("Parks");
                });
#pragma warning restore 612, 618
        }
    }
}
